version: '3'
services:
  ngnix:
    build:
      context: .
      dockerfile: ./docker/ngnix.dockerfile
    image: vinicius/ngnix
    container_name: ngnix
    ports: 
      - 8080
    networks:
      -  production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"
  
  mongodb:
    image: mongo
    networks:
      - production-network

  node1:
    build:
      context: .
      dockerfile: ./docker/alura-books.dockerfile
    image: vinicius/node1
    container_name: alura-books-1
    ports:
      - 3000
    networks:
      - production-network
    depends_on: 
      - "mongodb"

  node2:
    build:
      context: .
      dockerfile: ./docker/alura-books.dockerfile
    image: vinicius/node2
    container_name: alura-books-2
    ports:
      - 3000
    networks:
      - production-network
    depends_on: 
      - "mongodb"

  node3:
    build:
      context: .
      dockerfile: ./docker/alura-books.dockerfile
    image: vinicius/node3
    container_name: alura-books-3
    ports:
      - 3000
    networks:
      - production-network
    depends_on: 
      - "mongodb"

networks:
  production-network:
    driver: bridge